# Apply this file by kubectl create -f k8s/secret.yml
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: github-actions-secret
  annotations:
    kubernetes.io/service-account.name: github-actions
