apiVersion: v1
kind: ConfigMap
metadata:
  name: envread-settings
data:
  app.config.json: |-
    {
      "API_URL": "http://a2201d0f0638a476292e9df02a6959e7-9935b7554cdc1586.elb.us-east-1.amazonaws.com/api"
    }
