apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fe
  template:
    metadata:
      labels:
        component: fe
    spec:
      volumes:
        - name: envread-volume
          configMap:
            name: envread-settings
      containers:
        - name: fe
          image: 682755029646.dkr.ecr.us-east-1.amazonaws.com/fe-app-non-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: envread-volume
              mountPath: /usr/share/nginx/html/assets/
      imagePullSecrets:
        - name: regcred
