apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: fe
  template:
    metadata:
      labels:
        component: fe
    spec:
      containers:
        - name: fe
          image: 682755029646.dkr.ecr.us-east-1.amazonaws.com/fe-app-non-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
