name: base-action
on: pull_request
jobs:
  prime_base:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: extract branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Match branch name
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.branch-name.outputs.current_branch }}
          regex: '^(feat|feature|bugfix|bug)'

      - name: Check branch validity
        id: validity
        run: echo "validity=${{steps.regex-match.outputs.match || false}}" >> $GITHUB_OUTPUT

      - name: Check branch validity
        run: |
          if [[ ${{steps.validity.outputs.validity }} ==  false ]]; then
            echo "branch name is invalid"
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: lint
        run: npm run mulesoft:lint

      - name: test
        run: npm run mulesoft:test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: deploy
        run: echo 'Deployed successfully'
