name: Call reusable workflow
on: push
jobs:
  build_the_base:
    uses: ./.github/workflows/base-action.yml
    with:
      file-name: xyz.js
    secrets:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # print_the_output:
  #   needs: build_the_base
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: print the output
  #       run: echo "The output from reusable workflow is ${{ needs.build_the_base.outputs.my-output}}"

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build_the_base
  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v3

  #     - name: Download dist
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: mulesoft-app
  #         path: ./dist

  #     - name: Run custom action and deploy to s3
  #       id: deploy
  #       uses: ./.github/actions/deploy-s3-javascript
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         # This will set AWS env variable in ubuntu-latest and then aws cli on this machine can run aws command to
  #         # upload file to s3
  #       # call custom javascript action by passing below 2 parameters
  #       with:
  #         dist-folder: ./dist
  #         bucket: mulesoft-app-bucket

  # - name: Print the url of file uploaded to s3
  #   run: echo "The live url is ${{ steps.deploy.outputs.s3-url }}"
