name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
        # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
