# This will call reusable workflow file base-workflow.yml
name: Push to main branch
on:
  push:
    branches:
      - main
env:
  BUCKET_NAME: mulesoft-app-bucket1
  AWS_REGION: us-east-1
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  base-workflow:
    uses: ./.github/workflows/base-workflow.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    needs: base-workflow
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        # This step must be called to use your own action (the next step)

      - name: Install dependencies
        uses: ./.github/actions/cache-deps

      - name: Generate build
        run: npm run mulesoft:build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/apps/mulesoft/

  upload-to-s3:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::972267709493:role/githubdemo
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to s3
        run: aws s3 sync ./dist s3://${{env.BUCKET_NAME}} --region ${{env.AWS_REGION}}
