# This will call reusable workflow file base-workflow.yml
name: Push to main branch
on:
  push:
    branches:
      - main
jobs:
  base-workflow:
    uses: ./.github/workflows/base-workflow.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        # This step must be called to use your own action (the next step)

      - name: Install dependencies
        uses: ./.github/actions/cache-deps

      - name: Generate build
        run: npm run mulesoft:build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/apps/mulesoft/

  upload-to-s3:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist

      - name: Upload to s3
        run: aws s3 sync ./dist s3://mulesoft-app-bucket1 --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
