name: Push to branch
on: push
permissions:
  id-token: write # Since we are using openID connect, id-token is used in combination with it.
  # The job or workflow run requires a permissions setting with id-token: write. More about it can be read
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect
jobs:
  base-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: lint
        run: npm run mulesoft:lint

      - name: test
        run: npm run mulesoft:test

  build-push-image-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::682755029646:role/ecs-access-for-github
          aws-region: 'us-east-1'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Mulesoft Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./docker-mulesoft-action
          push: true
          tags: 682755029646.dkr.ecr.us-east-1.amazonaws.com/mulesoft-connector-app-non-prod:latest
